# Directory parameters.
directory:
  # Input directory where the input files are stored.
  input: ./input
  # Images directory where the images are stored.
  images: ./input/images
  # Output directory where the output files are stored.
  out: ./out

# Seed for random number generator.
seed: 42

# Voxel grid parameters.
voxel_grid:
  # Size of the mesh grid on each axis.
  mesh_grid_size: 120
  # Minimum occupancy of a voxel to be considered valid.
  min_occupancy: 32
  # Minimum 3D point value in the world coordinates on the x-axis.
  x_min: -0.05
  # Maximum 3D point value in the world coordinates on the x-axis.
  x_max: 0.05
  # Minimum 3D point value in the world coordinates on the y-axis.
  y_min: -0.1
  # Maximum 3D point value in the world coordinates on the y-axis.
  y_max: 0.04
  # Minimum 3D point value in the world coordinates on the z-axis.
  z_min: -0.75
  # Maximum 3D point value in the world coordinates on the z-axis.
  z_max: -0.5
